Y LB Demo Content: components and pages
YCloudYUSA/y_lb_demo_content pull request #1
Opened 2023-01-10 13:40 UTC by andreyzb

2023-01-10 14:23 UTC, anpolimus requested changes

2023-01-10 14:41 UTC, andreyzb commented on config/install/migrate_plus.migration.y_lb_demo_page_home.yml
> +              uuid: "aaa3168a-883c-4899-938b-c4cd1ddcdf14"
It is not possible at the moment, due to the way LayoutBuilder holds references to inline blocks. If you check out the YML structure of the migration, you can see that is not a regular migration config. Thus migration_lookup won't work there.
I propose to pass this as phase 1 and think on enhancements for phase 2.

2023-02-14 17:55 UTC, anpolimus commented
@andreyzb sorry, my fault.
I was trying to find better approach but cant find it now. 
It looks like LB migrations needs some improvements for better migration API support.

2023-02-14 17:55 UTC, anpolimus approved these changes

2023-02-20 16:30 UTC, podarok approved these changes

2023-02-20 16:30 UTC, merged